metrics_interval: "10s"
metrics_port: 2112
database:
  dsn: "mysql:mypassword@tcp(127.0.0.1:3306)/test?parseTime=true&timeout=10s"
  max_open_conns: 100
  max_idle_conns: 100
  conn_max_lifetime: "180s"
  conn_idle_timeout: "120s"
  test_query: "SELECT 1"                # Fallback query
  query_file: "./queries.sql"           # Optional SQL file
  seed_query: "SELECT id FROM users ORDER BY RAND() LIMIT 5;" # New seed query
  query_template: "SELECT * FROM users WHERE id = ?"          # New query template
  query_interval: "1s"
  concurrent_workers: 5
  queries_per_worker: 1
  idle_connections: 5                   # Open extra idle connections per worker
